"""edited foregn keys made strict and add foregn key in task_monitor

Revision ID: 9828dcb93dee
Revises: 18639a434352
Create Date: 2025-11-11 12:26:35.960430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9828dcb93dee'
down_revision: Union[str, Sequence[str], None] = '18639a434352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
