"""added column c_email in employee

Revision ID: b0e113b6634d
Revises: 9828dcb93dee
Create Date: 2025-11-12 22:31:56.560748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e113b6634d'
down_revision: Union[str, Sequence[str], None] = '9828dcb93dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('c_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'c_email')
    # ### end Alembic commands ###
