"""add column billable in task_monitors

Revision ID: f4e266f4dca7
Revises: b0e113b6634d
Create Date: 2025-11-14 20:25:03.702626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e266f4dca7'
down_revision: Union[str, Sequence[str], None] = 'b0e113b6634d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_monitors', sa.Column('billable', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_monitors', 'billable')
    # ### end Alembic commands ###
